export const simulationConfig = {
	defaultSeed: 2026,
	defaultTruckCount: 20,
	defaultRoutePointCount: 50,
	routeStepDegrees: 0.001,
	minSpeed: 8,
	maxSpeed: 100,
	minEtaSpeedKmh: 12,
	speedVariationRange: 20,
	angleVariationRange: 20,
	maxActivityEvents: 8,
	highRiskThreshold: 0.72,
	mediumRiskThreshold: 0.36,
	lowSpeedPenaltyKmh: 35,
	mediumSpeedPenaltyKmh: 50,
	lowSpeedDelayPenalty: 7,
	mediumSpeedDelayPenalty: 4,
	riskZoneDelayPenalty: 5,
	delayRiskWeight: 45,
	routeBiasRiskWeight: 0.35,
	riskZoneRiskWeight: 0.18,
	delayMultiplier: 0.2,
	atRiskPenalty: 4,
	delayedPenalty: 2,
	completedPenalty: 0.3,
} as const;
